version: '3.7'

services:
  mysql:
    image: mariadb:10.3.13
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: lang_report
    ports:
      - 3306:3306
    networks:
      - db-migrate
    command:
      - "--sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_general_ci"
    restart: always

networks:
  db-migrate:
